### ISSUE TITLE
No ST Auto-Updates on Windows

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing-gtk#331]
Hi,

after upgrading two Windows (8.1 x64) to the latest ST-GTK (v9.2.2), I noticed that the daemon has not been auto-updated (even though the checkbox is checked).

I had to manually remove the `syncthing.exe` inside `AppData/local/syncthing` , but even then ST-GTK would only download daemon v14.4. This is weird since the latest changelog states that ST-GTK is compatible to at least daemon v14.6..?

I manually upgraded the `syncthing.exe` to v14.9, seems to work, even though I know this is not a recommended behaviour ;)

I'd love an auto-update option for the whole ST-GTK on Windows by the way! :)

**Comment by kozec** [comment]
Hmm... [Last tag](https://github.com/syncthing/syncthing-gtk/releases) _is_ Syncthing_v0.14.9, so it should be finding update. I'll check what got broken.

Autoupdater for entire thing is planned, but that kind of stuff is rather crazy on Windows thanks to UAC, so that's point where I got stuck :D

**Comment by kozec** [comment]
Ok, it looks like I added last two to wrong commit. It should be fixed.

**Comment by acidicX** [comment]
> Ok, it looks like I added last two to wrong commit. It should be fixed.

I can confirm that, ST-GTK now updates to daemon v14.9. Thanks!

> Autoupdater for entire thing is planned, but that kind of stuff is rather crazy on Windows thanks to UAC, so that's point where I got stuck :D

Nice! I think most of the larger software vendors add a service that can auto-update, then you only have to accept UAC once. Otherwise, there is the popup-solution ("do you want to update?") which triggers the download and launches the installer, but that means accepting UAC every time you update ST-GTK. Ugly UX-wise, but it works and it's probably less time-consuming than writing your own windows service.

**Comment by ceribik** [comment]
This is still broken. It won't update the syncthing binary on Windows.

**Comment by acidicX** [comment]
I can confirm that

**Comment by kozec** [comment]
Weird. What ST-GTK version is reported by about dialog?

**Comment by acidicX** [comment]
I used the latest release (0.9.2.3) on two machines

**Comment by kozec** [comment]
Ok, I cleaned up tags a little and verified that updater recognizes 0.14.18 as most recent. It should work now.

On plus side, at least you were spared of that madness with symlinks that 0.14.13(?) caused :)

**Comment by seiferflo** [comment]
Hi @kozec .
I'm still on SC 0.14.38-rc1 on all my Windows computer (7/10/10). It's been a while I'm pushing updates manually as well. I tried turning on/off the autoupdate feature but it doesn't change anything. 
Any idea please ?

**Comment by kozec** [comment]
It will not auto-update to -rc version, but it should download version .39 when once-per-day timer expires.

**Comment by seiferflo** [comment]
Well it doesn't. I've just deleted syncthing.exe and forced Gtk to download the latest version, let's see whether it will get updated on futures updates.

**Comment by acidicX** [comment]
> It will not auto-update to -rc version

It does on Windows.

I can confirm what @seiferflo said - I had two Windows machines also auto-update to `-rc` versions and they did not upgrade the new patch (e.g. `.38-rc1` does not update automatically to `.38` final).

**Comment by kozec** [comment]
Ok, to rephrase that, it's not _supposed_ to :D

On other hand, if it already is at .38-rc1, comparing that to .38 may end in not upgrading as number is the same. I'll check if that's the case.

**Comment by seiferflo** [comment]
Hi. Once again, it's still not updating. Currently on 0.14.41 that I updated manually few weeks ago. No update on Win7x64 & Win10x64. The Syncthing package on my synology is updated to 0.14.43

**Comment by kozec** [comment]
@seiferflo Did it got updated after you posted?

**Comment by seiferflo** [comment]
Hi @kozec . Yes, did you change anything?

**Comment by kozec** [comment]
@seiferflo I've added git tag that says ST-GTK can update up to 0.14.43 day or two ago, but checks are done only once per day, so it's normal it lags a little.
